### ISSUE TITLE
Corruption of some image frames after anonymization

### ISSUE THREAD

**Issue by ringle** [horosproject/horos#42]
The anonymize tool results in corruption of some frames in multi-slice or multi-frame MRI datasets.  The attached screenshots show an MRI time series before and after anonymization.  Anonymization results in frames with question-mark thumbnails.  These corrupt frames are displayed as an image with a vertical white-to-black gradient.  The total number of image frames remains constant after anonymization, suggesting that some frames are corrupted during the anonymization process.

MRI Time Series Before Anonymization:
![mri_time_series_before_anonymization](https://cloud.githubusercontent.com/assets/6827215/11748794/ed99577a-9fde-11e5-85e0-057e0f4bfe0d.png)

MRI Time Series After Anonymization:
![mri_time_series_after_anonymization](https://cloud.githubusercontent.com/assets/6827215/11748797/f2afc906-9fde-11e5-9751-4bdb261b827c.png)

Good Frame (left) and Bad Frame (right) After Anonymization:
![good_bad_frame_after_anonymiaztion](https://cloud.githubusercontent.com/assets/6827215/11748800/f4fb0f86-9fde-11e5-92bb-e641040bbaea.jpg)

**Comment by tguiot** [comment]
Hi,
just wanted to let you know that I'm having exactly the same problem.
My source data are PET/CT images; I use the anonymize tool to modify the Patient's name, patient's ID and accession number and I also have random frames ending up empty. I use the "add" option and not "replace" or "export".
When I repeat the process, at some point, I'll have a complete set of images, but I have to do it several times...

EDIT: actually it's almost impossible to have a successful anonymization on a large set of files. So I had to switch back to Osirix to do the job...

**Comment by jensen0914** [comment]
I have the same issue if I use the Meta Data tool to edit a header. Upon reimporting the images, some slices/frames have corrupt/missing pixel data.

**Comment by reenot** [comment]
Same problem here.  I lose some images every time I anonymize.  I'm working with multi-slice, muti-(temporal) phase images.  I get a dicom of zeros and it appears to occur on random images in the series.  I also am having to go back to osirix.  Any fix would be greatly appreciated!

**Comment by fvpolpeta** [comment]
Hi;

We are working hard to have this fixed in version 2.0 of Horos, which is planned to be released in early June.

Please, try this nightly build: 

https://dl.dropboxusercontent.com/u/15111870/PurView/Horos%202016-05-15%2012-42-13.zip

=> El Capitan Required
=> Plugin momentarily disabled.

Please, your feedback is appreciated.

Best Regards

**Comment by ringle** [comment]
Thanks for working on fixing this issue.  I tried the build linked above, but the issue still persists.  I tried anonymizing several studies.  Some anonymized successfully, but others had a few corrupt frames after anonymization.  The corrupt frames seem to be random.  For example, I anonymized the same study twice, and different frames were corrupt in the two anonymized studies.

**Comment by fvpolpeta** [comment]
Please confirm how large are these series and which modality.

Tks for your help.

**Comment by reenot** [comment]
Same issue as Reeve.  I've anonymized the same study twice with different frames corrupted each run.  I'm working with MRI dicoms, in one exam there are roughly 60-80 series, with up to 225 images per series.

**Comment by ringle** [comment]
All are MR Modality.  The problem occurs when anonymizing large, medium, or small-sized series (in terms of number of frames).  For example, I independently anonymized series with 880 image frames, 40 image frames, and 3 image frames, and each of these had some corrupt frames.  Images frames are between 40 and 85 KB in each of these examples.

**Comment by fvpolpeta** [comment]
Please, could you try this new build and let me know results.

https://dl.dropboxusercontent.com/u/15111870/PurView/Horos%202016-05-17%2020-45-44.zip

Using this build I have been able to anonymize series with virtually any number of images of different modalities.

Look forward to hearing from you.

Tks

**Comment by fvpolpeta** [comment]
Also, send me a corrupted series for analysis.

Tks

**Comment by ringle** [comment]
No, this new build (2020-45-44) still has the same issue.  I will send you the resulting corrupted anonymized series.

**Comment by fvpolpeta** [comment]
If you have it after successful anonymization in OsiriX, send them too.

Tks

**Comment by tguiot** [comment]
I'm also still having the same problem with the latest build.

I uploaded a zip file containing the original data and the data after horos anonymization on wetransfer: https://we.tl/0cuHJ1a76b (available for 1 week)

It's a PET/CT examination, with one CT and three PT series. Corrupt files are random. In this particular set, there's one corrupt slice (out of 884) on the CT series (number 137).

In the anonymization process, I change only the Accession number, Patient name, and Patient ID; and I choose "Add"

I don't have Osirix anymore and don't want to reinstall so cannot send the result of the Osirix anonymization

**Comment by fvpolpeta** [comment]
I was able to reproduce the problem. Working to find out cause and then solve.

I will let you know.

Tks for your cooperation

**Comment by fvpolpeta** [comment]
Hey there;

Here is a build that, in principle, has the anonymization problem fixed.

https://dl.dropboxusercontent.com/u/15111870/PurView/Horos%202016-05-18%2022-27-50.zip

Please, let me know your results.

BR

**Comment by ringle** [comment]
Anonymization doesn't seem to be working in this build.  I tried both "Add" and "Replace" from the anonymization window, but no new studies were created.

**Comment by fvpolpeta** [comment]
Please, try this build and let me know your findings. The release of version 2.0.0 of Horos will happen soon and your feedback is welcome.

https://dl.dropboxusercontent.com/u/15111870/PurView/HorosNightly.dmg

Best Regards

Fauze

**Comment by ringle** [comment]
Anonymization works for me in this build, and I didn't notice any problems with corrupted frames.  Thanks!

**Comment by jardakotesovec** [comment]
@fvpolpeta Fyi I had this issue using directly 

```
    [XMLController modifyDicom: params encoding: encoding];
```

which is still used on several places and likely will misbehave..  so I guess you will be replacing that with gdcm also before 2.0.0?

**Comment by tguiot** [comment]
Works for me too, thanks!

**Comment by fvpolpeta** [comment]
Thank you all. 

Jardakotesovec, now that anonymization is ok, I will proceed with fixing XMLController.

https://github.com/horosproject/horos/issues/94

Thank you for reporting this

**Comment by fvpolpeta** [comment]
Hey Jardakotesovec,

I would like to request you to test the following build:

https://dl.dropboxusercontent.com/u/15111870/PurView/HorosNightly.dmg

In this build GDCM is place of DCMTK for DICOM metadata edition. Code still needs some cleanup.

If everything is ok I will close Issue #94
