### ISSUE TITLE
2D Viewer Annotations gone missing

### ISSUE THREAD

**Issue by fvpolpeta** [horosproject/horos#535]
"I can't seem to find out why the radio density values don't show up in the annotations anymore"

**Comment by jensen0914** [comment]
From original reporter: "The Mouse Position (px) already appears in the Annotations preferences but it does not show up on the images after I close preferences. [...] You can see the image in the background and it doesn't change when I quit annotations. Nothing but Image size and View size show up afterwards. I'm using a MacBook Pro running Catilina 10.15.2."

**Comment by jensen0914** [comment]
I cannot reproduce the missing annotation with Horos 4.0.0RC3 on my own MacBook Pro running macOS 10.15.2.in the preview window on the Database window or 2D Viewer windows. I can remove/re-add the annotation using the preferences and see the change (requires me to quit and relaunch Horos).

**Comment by jensen0914** [comment]
Switch color profiles in the Display preferences can reproduce this issue. Changing from the default "Color LCD" profile on my MacBook Pro to "ACES CG Linear" profile resulted in missing annotations. More than the pixel value was missing (e.g., WW/WL). Can reproduce with Horos 3.3.5 and 4.0.0RC3 on macOS 10.15.3.

**Comment by MSherafati** [comment]
I using MacBook Pro with macOS Catalina version 10.15.3. I have noticed the same annotation issue in the 2D viewer. Particularly, a few items on the left-side annotations are missing including "#im" and voxel specifications.

**Comment by bob831009** [comment]
I using Macbook Pro with macOS Catalina 10.15.3. I have the same issue that some annotation, such as im and zoom, are missing. Both Horos 4.0.0RC3 and Horos 3.3.6 are tried.

**Comment by ClaraPC** [comment]
I cannot see UH as an annotation. 
I am using macOS Catalina 10.15.5 and Horos v3.3.6

**Comment by jensen0914** [comment]
> I cannot see UH as an annotation.
> I am using macOS Catalina 10.15.5 and Horos v3.3.6

This is fixed in Horos v4.0.0RC4. You will have this issue with any version prior to that.

**Comment by ClaraPC** [comment]
Thank you for your quick reply. But I still have this problem with v4.0.0RC4. How could I fix it?

**Comment by jensen0914** [comment]
The workaround is to try using a different color profile for your display. Go to your macOS System Preferences->Displays->Color pane and try using a different display profile.

**Comment by ClaraPC** [comment]
Thank you so much. It works now!

**Comment by jensen0914** [comment]
Glad to hear. But I'm wondering if v4.0.0RC4 also did fix it. When you installed it, was Horos 3.3.6 still running? Because if it was, even if you overwrote the app file, then 3.3.6 was still the actual running version. Would you mind checking by opening the Horos->About Horos to see the version that is running. And if 3.3.6, trying to Quit and relaunch?

**Comment by ClaraPC** [comment]
I guess you may be right. 
v4.0.0RC4 is running now. I first uninstalled the previous version and then installed the newest one. I couldn't see any improvement, so I also changed the color of the display as you recommended. But again, there wasn't any change, so I went back to the previous color display. It was after all of this that I realized it works.

**Comment by BcSkier** [comment]
I am having similar problems on an imac.  I've tried to load the latest horos version but am now running 4.0.0.  I still have no annotation of the window and level on any of my dicom image windows.  Do I still need to find the v4.0.0RC4 version for my imac?
